; 1. CABEÇALHO DE IDENTIFICAÇÃO

;FIAP
;PCM
;NAC 02 EX 2
;ALUNOS:
;IGOR TOMAZELLI NIETMANN - RM: 82808
;JAN PETER MERKEL 		 - RM: 81896

; 2. ARQUIVO DE DEFINIÇÃO DO MICROCONTROLADOR
#INCLUDE <P18F452.INC>

; 3. DEFINIÇÃO DE VARIÁVEIS
#DEFINE BOTAO_RB3 PORTB, 3
#DEFINE BOTAO_RB4 PORTB, 4

#DEFINE LED_D0 PORTD, 0
#DEFINE LED_D1 PORTD, 1

; 3.1 GERAIS

CBLOCK 0x80            ; ENDEREÇO INICIAL DA MEMÓRIA DE DADOS
    FILTRO            ; VARIÁVEL FILTRO PARA O BOTÃO
    ESTADO             ;ESTADO = 0 -> INTERRUPTOR DESLIGADO | ESTADO = 1 -> INTERRUPTOR LIGADO

ENDC

; 3.2 CONSTANTES

T_FILTRO EQU .255        ; CONSTANTE T_FILTRO COM 230 DECIMAL
ZERO EQU B'00000000'    ; CONSTANTE COM VALOR ZERO

; 4. VETOR DE RESET
ORG 0x00 
GOTO INICIO

; 5. INÍCIO DO PROGRAMA 
; CONFIGURAÇÕES INICIAIS (REGISTRADORES DE FUNÇÕES ;ESPECIAIS)
INICIO
    CLRF PORTD             ; LIMPA PORTD (ESCREVE ZERO EM TODOS OS PINOS DO PORTD)
    MOVLW B'00011000'     ; MOVE O VALOR BINÁRIO PARA O REGISTRADOR WORK 
    MOVWF TRISB         ; DEFINE RB3 E RB4 COMO ENTRADA E DEMAIS COMO SAÍDA
    MOVLW B'00000000'     ; MOVE O VALOR BINÁRIO PARA O REGISTRADOR WORK
    MOVWF TRISD         ; DEFINE TODOS OS TERMINAIS DO PORTD COMO SAÍDA

; 6. FUNÇÃO PRINCIPAL
MAIN
    MOVLW T_FILTRO
    MOVWF FILTRO
    MOVLW ZERO
    MOVLW ESTADO

    VERIFICA_ESTADO
    BTFSC ESTADO, 0        ;O INTERRUPTOR ESTÁ ATIVADO?
    GOTO LIBERAR_AGUA    ;SIM VÁ PARA A LOGICA DE LIBERAÇÃO DE ÁGUA
    VERIFICAR_BOTAO        ;NÃO, VERIFIQUE SE O BOTÃO ESTÁ ATIVADO PARA MUDAR O ESTADO
    BSF LED_D1
    BTFSC BOTAO_RB3        ;BOTAO ESTÁ PRESSIONADO
    GOTO MAIN
    DECFSZ FILTRO, 1
    GOTO VERIFICAR_BOTAO

    LIBERAR_AGUA
    BCF LED_D1
    BSF ESTADO, 0
    BSF LED_D0
    GOTO MAIN






END